site_name: Payphone Club
site_description: Let's share information about payphones! Whether you just want to learn about different kinds of payphones, are considering procuring one for yourself, or want to operate your own payphone organization, we are here to help!

repo_url: https://github.com/payphone-club/payphone-club.github.io
edit_uri: blob/main/docs/

nav:
  - Home: index.md
  - Identification:
    - Identification: identification/README.md
    - 3-Slot: identification/3-slot-payphones.md
    - Single-Slot: identification/single-slot-payphones.md
  - Acquisition: acquisition/README.md

plugins:
  - mkdocs-image-captions
