site_name: Payphone Club

repo_url: https://github.com/payphone-club/payphone-club.github.io
edit_uri: blob/main/docs/

nav:
  - Home: index.md
  - Identification:
    - Identification: identification/README.md
    - 3-Slot: identification/3-slot-payphones.md
    - Single-Slot: identification/single-slot-payphones.md
  - Acquisition: acquisition/README.md

plugins:
  - mkdocs-image-captions
